version: "3"

volumes:

  hadoop_namenode:
  hadoop_datanode:
  shared-workspace:
    external: true
  postgres-data:

services:

  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: newdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  hive:
    image: hive
    container_name: hive
    restart: always
    ports:
     - "54310:54310"
     - "54311:54311"
     - "9870:9870"
     - "5349:5349"
     - "5249:5249"
    volumes:
      - hadoop_datanode:/opt/hadoop/hadoop_data/hdfs/datanode
      - hadoop_namenode:/opt/hadoop/hadoop_data/hdfs/namenode

  spark:
    image: spark
    container_name: spark
    restart: always
    ports:
      - "8080:8080"
      - "7077:7077"
      - "8081:8081"
      - "7000:7000"

  theia:
    image: theia
    container_name: theia
    ports:
      - "3000:3000"
    volumes:
      - shared-workspace:/home/project

  jupyter:
    image: jupyter
    container_name: jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - shared-workspace:/opt/workspace

#Jupyter
#https://www.kdnuggets.com/2020/07/apache-spark-cluster-docker.html

#Theia
#https://github.com/theia-ide/theia-apps

