version: "3"

# Build external workspace: 

volumes:
  #hadoop_namenode:
  #hadoop_datanode:
  #hadoop_historyserver:
  shared-workspace:
    external: true
  postgres-data:
  #shared-workspace:
  #   driver: local
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     #device: "C:\\Users\\at0744799\\projects\\docker\\cluster\\data"
  #     device: //c/Users/at0744799/projects/docker/cluster/data/

services:

  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: newdb
    ports:
      - "5432:5432"
    #network_mode: bridge
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    #network_mode: bridge

  hadoop:
    image: hadoop
    container_name: hadoop
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
      - "9864:9864"
      - "10000:10000"
      - "9999:9999"
      - "9083:9083"

  spark:
    image: spark
    container_name: spark
    restart: always
    ports:
      - "8080:8080"
      - "7077:7077"
      - "8081:8081"

  ide:
    # $theia/docker build -t theia .
    # docker run -it --init -p 3000:3000 theia:latest
    image: ide
    container_name: ide
    ports:
      - "3000:3000"
    volumes:
      - shared-workspace:/home/project
    #network_mode: bridge

  jupyterlab:
    # $jupyter/docker build -t jupyter .
    image: jupyter
    container_name: jupyterlab
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - shared-workspace:/opt/workspace

#Jupyter
#https://www.kdnuggets.com/2020/07/apache-spark-cluster-docker.html

#Theia
#https://github.com/theia-ide/theia-apps

